name: countdown
description: Countdown is countdown with pause/resume controls
version: 0.0.4
author: Benjamin NGUYEN <benjamin.kim.nguyen@gmail.com>
homepage: https://github.com/BenNG/countdown
dev_dependencies:
  quiver: any
environment:
  # Works in Dart 1 (starting with 1.20.1), and works in Dart 2.
  sdk: '>=1.20.1 <3.0.0'

